address_descriptors = false
author = "Themefisher"
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
custom_script = ""
description = "This is meta description"
email = "demo@email.com"
favicon = "images/newfavicon.png"
google_tag_manager = ""
image = "images/newlogo.png"
location = "**Themefisher**  \nNorth Main Street  \nBrooklyn, New South Wales  \nAustralia\n"
logo = "images/newlogo.png"
logo_text = "Open Applied Linguistics Research Network"
logo_width = "80px"
navbar_fixed = false
phone = "0124857985320"
recaptcha_site_key = "xxx-xxxxxxxxxxxxxxxxxxxxxxxx"
[baidu]
analytics_id = ""
enable = false
[contact.form]
action = "#"
enable = false
success_image = "images/paper-plane.svg"
use_netlify = false
use_recaptcha = false
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[counter]
enable = false
username = ""
[gmap]
enable = true
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[matomo]
enable = false
id = ""
url = ""
[navigation_button]
enable = false
label = "get a quote"
link = "contact"
[plausible]
domain = ""
enable = false
[preloader]
enable = true
preloader = ""
[site_verification]
baidu = ""
bing = ""
google = ""
[widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[social]]
icon = "fab fa-twitter"
link = "#"
title = "twitter"
